import type { Metadata } from "next";
import localFont from "next/font/local";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import { ThemeProvider } from 'next-themes'
import { Header } from "@/components/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const sansFont = localFont({
  src: "../../public/fonts/sans-regular.woff2",
  weight: "400",
  style: "normal",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`antialiased text-base md:text-sm bg-white dark:bg-neutral-900 ${inter.className}`}
      >
        <ThemeProvider attribute="class">
          <Header />
          <main className="min-h-screen">
            <div className="page pt-16 px-4 md:px-0 pb-28 mx-auto md:w-[560px] xl:w-[720px]">
              {children}
            </div>
          </main>
          <footer className="footer"></footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
